"""
Part II end-to-end demo: fit a CurvatureField (Part I) from synthetic
snapshot data generated by a known, curl-free "simulator", train four
flow-matching methods against it, and compare them via velocity alignment
(the recipe's Stage 6 primary metric) plus W2.

Methods compared:
    OT-CFM      -- plain optimal-transport conditional flow matching (A=0)
    scalar-c    -- isotropic per-segment curvature (Stage A.4 ablation:
                   isolates whether *anisotropy* earns its parameters)
    global-A    -- a single non-spatial anisotropic A per segment (isolates
                   whether *position dependence* earns its parameters)
    full-field  -- the full position/time-dependent A(x,t) field (Part I),
                   coupled via Stage 4's per-candidate-pair field cost

A flexible-interpolant (spline/ALI-CFM) baseline is intentionally not
included -- the recipe itself de-emphasizes it ("do not claim superiority
as a curve-fitter"). Real single-cell data integration (see
examples/single_cell/eval_loo_methods.py for the analogous LOO harness
against real eb/cite/multiome datasets) is a future extension point, not
implemented here -- this script is synthetic-only, verifying the pipeline
against a KNOWN ground-truth velocity field before any real-data run.

Usage:
    python train_field_flow_matching.py
    python train_field_flow_matching.py --d 3 --n-per-knot 800 --n-iter 2000
    python train_field_flow_matching.py --methods OT-CFM full-field
"""

import argparse
import time

import numpy as np
import torch

from torchlfm.conditional_flow_matching import (
    ExactOptimalTransportConditionalFlowMatcher,
    ExactOptimalTransportMatrixHarmonicConditionalFlowMatcher,
    FieldMatrixHarmonicConditionalFlowMatcher,
)
from torchlfm.curvature import clamp_spectrum
from torchlfm.curvature_field import CurvatureField
from torchlfm.curvature_fitting import (
    contraction_ratios_from_cov,
    fit_isotropic_scalar,
    fit_straddling_segment_from_cov,
    segment_covariances,
)
from torchlfm.field_coupling import make_field_ot_sampler
from torchlfm.field_training import make_field_segment_batch, make_plain_segment_batch, train_field_flow_matching
from torchlfm.optimal_transport import wasserstein
from torchlfm.synthetic_ground_truth import curl_free_force, integrate_snapshots
from torchlfm.velocity_eval import evaluate_velocity_alignment, integrate_model_trajectory

ALL_METHOD_NAMES = ["OT-CFM", "scalar-c", "global-A", "full-field"]

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ---------------------------------------------------------------------------
# Simulator + dataset
# ---------------------------------------------------------------------------


def build_simulator(d: int, rng: np.random.Generator):
    """A genuinely nonlinear, curl-free force (torchlfm.synthetic_ground_truth),
    STATIC on purpose -- see that module's docstring for why this is a
    harder test than an in-family piecewise-constant-A ground truth."""
    Q, _ = np.linalg.qr(rng.standard_normal((d, d)))
    lam0 = rng.uniform(-1.5, 1.5, size=d)
    A0 = (Q * lam0) @ Q.T
    eps = 0.03
    c = np.ones(d)

    def force_fn(X):
        return curl_free_force(X, Q, A0, eps, c)

    return force_fn


def build_dataset(args, rng: np.random.Generator):
    force_fn = build_simulator(args.d, rng)
    # off-origin (checklist item: subpopulations not centred at the origin)
    mu0 = rng.uniform(1.5, 3.0, size=args.d)
    x0 = rng.normal(loc=mu0, scale=1.0, size=(args.n_per_knot, args.d))
    times = np.linspace(0.0, args.t_max, args.n_knots)
    snapshots = integrate_snapshots(x0, times, force_fn)
    return snapshots, times, force_fn


# ---------------------------------------------------------------------------
# Method registry: one list of per-segment batch closures per method
# ---------------------------------------------------------------------------


def build_methods(snapshots, times, args, rng: np.random.Generator) -> dict:
    methods = {name: [] for name in ALL_METHOD_NAMES}
    field = None
    if "full-field" in args.methods:
        field = CurvatureField.fit(
            snapshots, times, m_nn=args.m_nn, max_anchors_per_knot=args.max_anchors_per_knot, rng=rng
        )

    n_knots = len(snapshots)
    for j in range(1, n_knots - 1):
        X_left, X_mid, X_right = snapshots[j - 1], snapshots[j], snapshots[j + 1]
        t0, dt = float(times[j - 1]), float(times[j + 1] - times[j - 1])

        if "OT-CFM" in args.methods:
            fm_plain = ExactOptimalTransportConditionalFlowMatcher(sigma=0.0)
            methods["OT-CFM"].append(make_plain_segment_batch(X_left, X_right, fm_plain, None, t0, dt))

        if "scalar-c" in args.methods or "global-A" in args.methods:
            Sig_s, Sig_m = segment_covariances(X_left, X_right, X_mid)

        if "scalar-c" in args.methods:
            rho = contraction_ratios_from_cov(Sig_s, Sig_m)
            c_k = fit_isotropic_scalar(rho)
            A_scalar = clamp_spectrum(c_k * np.eye(args.d))
            fm_scalar = ExactOptimalTransportMatrixHarmonicConditionalFlowMatcher(
                sigma=0.0, A=torch.as_tensor(A_scalar, dtype=torch.float)
            )
            methods["scalar-c"].append(make_plain_segment_batch(X_left, X_right, fm_scalar, None, t0, dt))

        if "global-A" in args.methods:
            A_global = fit_straddling_segment_from_cov(Sig_s, Sig_m)
            fm_global = ExactOptimalTransportMatrixHarmonicConditionalFlowMatcher(
                sigma=0.0, A=torch.as_tensor(A_global, dtype=torch.float)
            )
            methods["global-A"].append(make_plain_segment_batch(X_left, X_right, fm_global, None, t0, dt))

        if "full-field" in args.methods:
            sampler, cache = make_field_ot_sampler(field, t_bar=float(times[j]))
            fm_field = FieldMatrixHarmonicConditionalFlowMatcher(sigma=0.0)
            methods["full-field"].append(
                make_field_segment_batch(X_left, X_right, fm_field, sampler, cache, t0, dt)
            )

    return {name: closures for name, closures in methods.items() if closures}


# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------


def evaluate(model, snapshots, times, force_fn, args, rng: np.random.Generator) -> dict:
    model.eval()

    # Velocity alignment (Stage 6 primary metric): query points pooled from
    # every snapshot, at their own snapshot's time, against the known
    # simulator velocity -- index-safe by construction (evaluate_velocity_alignment).
    all_x, all_t = [], []
    for x, t in zip(snapshots, times):
        all_x.append(x)
        all_t.append(np.full(x.shape[0], t))
    all_x = np.concatenate(all_x)
    all_t = np.concatenate(all_t)
    idx = rng.choice(all_x.shape[0], size=min(args.n_eval, all_x.shape[0]), replace=False)
    x_eval = torch.as_tensor(all_x[idx], dtype=torch.float32)
    t_eval = torch.as_tensor(all_t[idx], dtype=torch.float32)
    valign = evaluate_velocity_alignment(model, x_eval, t_eval, force_fn, device=device)

    # W2 (secondary -- treat with suspicion at higher d, per the recipe's
    # own warning that oracle improvement over OT-CFM fades with dimension).
    x0 = torch.as_tensor(snapshots[0], dtype=torch.float32)
    t_span = torch.linspace(float(times[0]), float(times[-1]), args.integration_steps + 1)
    traj = integrate_model_trajectory(model, x0.to(device), t_span.to(device))
    pred_final = traj[-1].cpu()
    target_final = torch.as_tensor(snapshots[-1], dtype=torch.float32)
    w2 = wasserstein(pred_final, target_final, power=2)

    return {**valign, "w2": w2}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--d", type=int, default=3, help="embedding dimension")
    parser.add_argument("--n-knots", type=int, default=5, help="number of snapshot timepoints")
    parser.add_argument("--n-per-knot", type=int, default=600, help="cells per snapshot")
    parser.add_argument("--t-max", type=float, default=4.0, help="final simulation time")
    parser.add_argument("--n-iter", type=int, default=1000, help="training iterations per method")
    parser.add_argument("--batch-size", type=int, default=128)
    parser.add_argument("--m-nn", type=int, default=40, help="anchor neighbourhood size (CurvatureField)")
    parser.add_argument("--max-anchors-per-knot", type=int, default=60)
    parser.add_argument("--n-eval", type=int, default=500, help="query points for velocity alignment")
    parser.add_argument("--integration-steps", type=int, default=50)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--methods", nargs="+", default=ALL_METHOD_NAMES, choices=ALL_METHOD_NAMES)
    args = parser.parse_args()

    torch.manual_seed(args.seed)
    rng = np.random.default_rng(args.seed)

    print(f"Building synthetic dataset (d={args.d}, n_knots={args.n_knots}, n_per_knot={args.n_per_knot})...")
    snapshots, times, force_fn = build_dataset(args, rng)

    print(f"Building method specs: {args.methods}")
    methods = build_methods(snapshots, times, args, rng)

    results = {}
    for name, segment_batch_fns in methods.items():
        print(f"Training {name} ({args.n_iter} iterations)...")
        t_start = time.time()
        model = train_field_flow_matching(
            segment_batch_fns, dim=args.d, n_iter=args.n_iter, batch_size=args.batch_size, device=device
        )
        elapsed = time.time() - t_start
        metrics = evaluate(model, snapshots, times, force_fn, args, rng)
        metrics["train_seconds"] = elapsed
        results[name] = metrics

    header = f"{'method':<12} {'cos_dist':>10} {'norm_l2':>10} {'w2':>10} {'train_s':>10}"
    print("\n" + header)
    print("-" * len(header))
    for name, m in results.items():
        print(
            f"{name:<12} {m['cosine_distance_mean']:>10.4f} {m['normalized_l2_mean']:>10.4f} "
            f"{m['w2']:>10.4f} {m['train_seconds']:>10.1f}"
        )


if __name__ == "__main__":
    main()
